### ISSUE TITLE
The space key does not work in the add bot field

### ISSUE THREAD

**Issue by reddeath68** [MaggiWuerze/xddcwebloader#60] opened 2022-08-16 22:23 UTC

**Comment by MaggiWuerze** [comment] 2022-08-17 07:49
Apparently this was caused by the Nav element surrounding the button and popover root. The error is fixed in master I just need to make some UI adjustments before creating a new release

**Comment by MaggiWuerze** [comment] 2022-08-22 14:07
Fixed in [v0.5.3-BETA](https://github.com/MaggiWuerze/xddcwebloader/tree/v0.5.3-BETA)

**Closed by MaggiWuerze** 2022-08-22 14:07 UTC
